name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Atau branch lain yang ingin Anda gunakan untuk deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Gunakan versi terbaru

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Gunakan versi terbaru
        with:
          node-version: '20'  # Pastikan menggunakan versi Node.js yang sesuai

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: npm run firebase